server {
    listen 80;
    
    resolver 127.0.0.11 valid=30s;
    
    location /api/ {
        set $backend http://backend:8080;
        proxy_pass $backend/api/;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}