package model

import "errors"

var (
	ErrEmptyTitle          = errors.New("title is empty")
	ErrNegativeAmount      = errors.New("amount is negative")
	ErrInvalidID           = errors.New("invalid id")
	ErrNotFoundExpense     = errors.New("not found id")
	ErrTooLongTitle        = errors.New("title is to long")
	ErrInvalidMonth        = errors.New("invalid month")
	ErrEmptyDBURL          = errors.New("DB_URL is empty")
	ErrNotFound            = errors.New("not found")
	ErrInvalidCurrency     = errors.New("invalid currency")
	ErrEmptyAPIKey         = errors.New("API Key is empty")
	ErrZeroAmount          = errors.New("zero amount")
	ErrUserExists          = errors.New("user already exists")
	ErrIncorrectPassword   = errors.New("incorrect password")
	ErrEmptyJWTSecret      = errors.New("JWT Secret is empty")
	ErrInternal            = errors.New("internal error")
	ErrInvalidToken        = errors.New("invalid token")
	ErrInvalidLimit        = errors.New("invalid limit")
	ErrDBDown              = errors.New("db error")
	ErrSomething           = errors.New("something error")
	ErrInvalidYear         = errors.New("invalid year")
	ErrEmptyMonth          = errors.New("empty month")
	ErrEmptyAllowedOrigins = errors.New("empty allowed origins")
	ErrFutureDate          = errors.New("future or incorrect date")
	ErrFailedCreateToken   = errors.New("failed generate token")
	ErrEmptyReq            = errors.New("request is empty")
	ErrQuickAddDecimal     = errors.New("decimal amount")
	ErrQuickAddNoAmount    = errors.New("no amount")
	ErrTokenAuthNotAllowed = errors.New("token auth is not allowed for this operation")
	ErrRateUnavailable     = errors.New("rate is unavailable")
)
